# Generated by Django 3.2.7 on 2021-10-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211026_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (1, 'Average'), (1, 'Fine'), (1, 'Good'), (1, 'Great')], null=True),
        ),
    ]
