# Generated by Django 3.2.7 on 2021-10-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Average'), (3, 'Fine'), (4, 'Good'), (5, 'Great')], null=True),
        ),
    ]
